### ISSUE TITLE
Feature Request: Support of OpenSSL 3.0 (and up)

### ISSUE THREAD

**Issue by lloydbates** [paolo-rossi/delphi-jose-jwt#83]
It looks like the current implementation does not account for changes in OpenSSL 3.0 (and up).
The most current OpenSSL 1.1.1 had its End-Of-Life on 2023-09-11 [1] [2]

A general overview of the amount of changes for OpenSSL 3.0 exists as a migration guide [3]

[1] https://mta.openssl.org/pipermail/openssl-announce/2023-March/000254.html
[2] https://web.archive.org/web/20240703082539/https://www.openssl.org/blog/blog/2023/09/11/eol-111/
[3] https://docs.openssl.org/3.0/man7/migration_guide/

**Comment by paolo-rossi** [comment]
Hello @lloydbates 

thanks for the documentation about OpenSSL 3.x migration...

I too would like to port this library to to OpenSSL 3.x but I'm waiting for Embarcadero/IndyTeam to officially update Indy to OpenSSL 3.x otherwise you cannot use this library if you also use Indy with OpenSSL in your project, and given that the JWT stuff is used in conjunction with http communication this scenario is likely to happen..

I hope in the next months to see an update to Indy regarding OpenSSL, will see...

Paolo.
