### ISSUE TITLE
Example to encrypt using RS256 algorithm with pem file

### ISSUE THREAD

**Issue by fuandihartanto** [paolo-rossi/delphi-jose-jwt#9]
Hi, Any example to encrypt using RS256 ? I having problem with this. Currently I have private key in pem file and I don't know how to use it to encrypt the jwt.
Appreciate if you can help me with the example

**Comment by paolo-rossi** [comment]
Hi, 
sorry for now only HS* algorithms are supported,unfortunately Delphi doesn't have any decent cryptography library so to implement RS and ES algorithms I have to work at a very low level with the Open SSL library. Anyway.. you can always encrypt the payload for yourself if you need encryption.

Paolo.

**Comment by SirAlex** [comment]
I'm just finished initial work on RSA signing support. I have added support for RS256, RS384 and RS512 signing algorithms for your library. Please review code at my repo:

**Comment by paolo-rossi** [comment]
Hi SirAlex!

thank you very much for your work, why don't you open a Pull Request so I can merge your work into the main project and giving you the credit for the work?

After that I will adjust the code to match the project's code write standards (variable naming, etc...).
The only thing that you can do before open the PR is to rename the unit "JOSE.Cryptography.RSA.pas" in "JOSE.Signing.RSA.pas" because the RSA function used are only for the signing part.

Thank you again for yor code!

Paolo.
